swagger: "2.0"
info:
  title: "NUWS Water Utility - REST API"
  description: 'This is a _Minimum Viable Product (MVP)_ of a REST API that allows `NUWS` a water utility authority to report data to clients with different reporting requirements more efficiently. Through the API, the clients (_Ex. Development Partners, Research Institutes, Regulatory Authorities etc_) can interact with the API, view its documentation, and test its functionality. 
    This MVP REST API handles some endpoint view functions and not others. The implemented endpoints are the ones the clients can use to perform certain actions or retrieve information from the NUWS server on this page. As an MVP, priority was given to some features to illustrate the overall concept of integration. That way, with time, we can improve the API in general, and expose some more of the new other features.
    
    Some useful links:
    - [NUWS API Project repository](https://github.com/lukwagoraymond/nuws-api-v1)
    - [The source API definition for NUWS API](https://github.com/lukwagoraymond/nuws-api-v1/tree/pipeline/api)'
  contact:
    name: "Raymond Lukwago A.R"
    email: "lukwagoraymond3@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  version: "0.1.0"
host: 'http://127.0.0.1:5000'
basePath: '/nuws/api/v1.0'
schemes:
  - 'http'
consumes:
  - application/json
produces:
  - application/json
